version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - vendor:/app/vendor
    command: vendor/bin/phpunit --testsuite "Zendesk API Unit Test Suites"
    # command: vendor/bin/phpunit --filter testExceptionsRetry tests/Zendesk/API/UnitTests/Middleware/RetryHandlerTest.php

volumes:
  vendor:
