version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - vendor:/app/vendor
    command: vendor/bin/phpunit --testsuite "Zendesk API Unit Test Suites"
    # command: vendor/bin/phpunit tests/Zendesk/API/UnitTests/Traits/Utility/PaginationTest.php
    # command: vendor/bin/phpunit tests/Zendesk/API/UnitTests/Core/TicketsTest.php
    # command: vendor/bin/phpunit tests/Zendesk/API/UnitTests/Core/AppInstallationsTest.php

volumes:
  vendor:
